---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Build release api
    community.docker.docker_image:
      name: projectapi
      state: present
      build:
        path: /home/s116277/Desktop/apibuild/.
        args:
          build_version: 'Release'
      source: build
  - name: Start new api release container
    docker_container:
      name: apirelease
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5002:80