---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Copy api project to centos to build release version
    copy:
      src: /var/jenkins_home/workspace/API pipeline/ProjectAPI/
      dest: /home/s116277/Desktop/apibuild/
  - name: Build api
    command: "docker build --no-cache --build-arg build_version=Release -t projectapi /home/s116277/Desktop/apibuild/"
  - name: Start new api release container
    docker_container:
      name: apirelease
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5002:80