---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Build api
    docker_image:
      name: projectapi
      build:
        path: ~/Desktop/apibuild/.
        state: present
        args:
          build_version: 'Debug'
        source: build
  - name: Start new api test container
    docker_container:
      name: api
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5001:80