---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Build api
    command: "docker build -t projectapi /home/s116277/Desktop/apibuild/"
  - name: Start new api test container
    docker_container:
      name: api
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5001:80