---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Update image
    command: "docker build -t projectapi /home/s116277/Desktop/apibuild/"
  - name: Build api
    community.docker.docker_image:
      name: projectapi
      build:
        nocache: yes
        path: /home/s116277/Desktop/apibuild/.
        args:
          build_version: 'Debug'
      source: build
  - name: Start new api test container
    docker_container:
      name: api
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5001:80
