---
# Zet site in nginx container
- hosts: centosserver
  tasks:
  - name: Create nginx container
    docker_container:
      name: angulartestserver
      image: nginx
      state: started
      restart: yes
      volumes: 
        - /home/angularserver/:/usr/share/nginx/html
      ports:
        - 81:80
  - name: Copy angular build to nginx
    copy:
      src: ~/workspace/API pipeline/Website/space-api/dist/space-api
      dest: /home/angularserver/