---
# Maakt asp.net api docker container
- hosts: centosserver
  tasks:
  - name: Copy api project to centos to build release version
    copy:
      src: ~/workspace/API pipeline/ProjectAPI
      dest: /home/s116277/Desktop/apibuild/
  - name: Build release api
    community.docker.docker_image:
      name: projectapi
      build:
        nocache: yes
        path: /home/s116277/Desktop/apibuild/.
        args:
          build_version: 'Release'
      source: build
  - name: Start new api release container
    docker_container:
      name: apirelease
      image: projectapi
      state: started
      restart: yes
      ports:
        - 5002:80