---
#Playbook test
- hosts: centosserver
  tasks:
  - name: Create testfile
    file:
      path: "/home/s116277/Desktop/test.txt"
      state: touch
  - name: Add line to testfile
    lineinfile:
      dest: /home/s116277/Desktop/test.txt
      line: test1